name: CI Pipeline

on:
  push:
    branches:
      - dev
      - feature-*
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python linter
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install pylint
          pylint **/*.py || true



